// actionTypes.js
export const SET_GENERAL_QUESTIONS = "SET_GENERAL_QUESTIONS";
export const SET_PRIVATE_QUESTIONS = "SET_PRIVATE_QUESTIONS";
export const SET_ESTIMATE_QUESTIONS = "SET_ESTIMATE_QUESTIONS";
export const SET_IMAGES_GUESS = "SET_IMAGES_GUESS";
export const SET_VIDEOS_ZOOM = "SET_VIDEOS_ZOOM";

export const DELETE_GENERAL_QUESTIONS = "DELETE_GENERAL_QUESTIONS";
export const DELETE_PRIVATE_QUESTIONS = "DELETE_PRIVATE_QUESTIONS";
export const DELETE_ESTIMATE_QUESTIONS = "DELETE_ESTIMATE_QUESTIONS";
export const DELETE_IMAGES_GUESS = "DELETE_IMAGES_GUESS";
export const DELETE_VIDEOS_ZOOM = "DELETE_VIDEOS_ZOOM";
