// actionTypes.js
export const SET_QUESTIONS_GENERAL = "SET_QUESTIONS_GENERAL";
export const SET_QUESTIONS_PRIVATE = "SET_QUESTIONS_PRIVATE";
export const SET_QUESTIONS_ESTIMATE = "SET_QUESTIONS_ESTIMATE";
export const SET_IMAGES_GUESS = "SET_IMAGES_GUESS";
export const SET_VIDEOS_ZOOM = "SET_VIDEOS_ZOOM";

export const DELETE_GENERAL_QUESTIONS = "DELETE_GENERAL_QUESTIONS";
export const DELETE_PRIVATE_QUESTIONS = "DELETE_PRIVATE_QUESTIONS";
export const DELETE_ESTIMATE_QUESTIONS = "DELETE_ESTIMATE_QUESTIONS";
export const DELETE_IMAGES_GUESS = "DELETE_IMAGES_GUESS";
export const DELETE_VIDEOS_ZOOM = "DELETE_VIDEOS_ZOOM";
